---
namespace: shahargolshani
name: ansible.artifactory
version: 0.1.0
readme: README.md
authors:
  - Shahar Golshani <sgolshan@redhat.com>
  - Ilya Shavkonov <ishavkon@redhat.com>
description: Ansible Collection for Jfrog Artifactory
license_file: LICENSE
tags:
  - linux
repository: https://github.com/shahargolshani/ansible.artifactory 
homepage: https://github.com/shahargolshani/ansible.artifactory
issues: https://github.com/shahargolshani/ansible.artifactory/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
